### ISSUE TITLE
Erro para plotar os dados da estação

### ISSUE THREAD

**Issue by gabrielcocenza** [sehnem/pynmet#1]
Primeiramente gostaria de parabenizar pela iniciativa deste projeto.
Eu estou abrindo o pynmet pelo terminal e aparece o seguinte erro:

>>> import pynmet
>>> estacao = pynmet.inmet("A713")
>>> estacao.dados.Temperatura.plot()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pandas/plotting/_core.py", line 2453, in __call__
    **kwds)
  File "/usr/local/lib/python3.5/dist-packages/pandas/plotting/_core.py", line 1882, in plot_series
    import matplotlib.pyplot as plt
ImportError: No module named 'matplotlib'
>>> 

Além disso, não encontro o documento com os dados da estação no diretório $HOME. O único arquivo que aparece é um .inmetdb.hdf

Abraço

**Comment by sehnem** [comment]
A documentação da biblioteca está bem ruim, não tive muito tempo para trabalhar nela ainda, acho que não deixei claro algumas coisas.

Primeiramente, quanto ao seu erro, é falta do pacote matplotlib.
Dentro da classe inmet quando se carrega uma estação ele além dos dados do da estação ele cria um Dataframe do Pandas (.dados). O plot é um método do próprio pandas e o matplotlib é uma dependência opcional deste.
O comando `pip install matplotlib` deve resolver seu problema.

O banco de dados é o próprio arquivo .inmetdb.hdf, utilizei esse formato por ser mais eficiente em velocidade de tamanho.

Se preferir extrair os seus dados em um csv pode utilizar o comando abaixo
```
import pynmet
estacao = pynmet.inmet('A713')
estacao.dados.tz_convert(None).to_csv('~/A703.csv')
```
O método `.tz_convert(None)` é utilizado apenas para remover o fuso horário e gerar um formato de data mais limpo no .csv

Caso tenha mais alguma dúvida, ou mesmo sugestão fique a vontade para pergunta.

Abraço

**Comment by sehnem** [comment]
Agora li que você está utilizando pelo terminal. Nele as figuras não são exibidas, você terá que salva-las. Recomendo que utilize a biblioteca pelo spyder ou jupyter, irá facilitar muito o processo de análise e plotagem dos dados.
Se precisar de ajuda quanto a isso pode entrar em contato pelo hangout josue@sehnem.com

**Comment by gabrielcocenza** [comment]
Genial Josué! Parabéns cara. Você fez algo sozinho que era para o governo disponibilizar facilmente. Eu estava pensando em criar um algoritmo para quebrar o capcha do inmet o que para uma pessoa sem muita base computacional consumiria um bom tempo.  Tenho um conhecimento básico em Python (vide o erro idiota de falta de biblioteca).
Formatei meu computador recentemente e não parei para instalar o Pycharm (prefiro do que o spyder) e qualquer coisa eu volto a te perguntar. 
Abraço

**Comment by sehnem** [comment]
Foi justamente a dificuldade em obter os dados que me motivou a criar o pacote para a quebra do captcha.
Infelizmente o INMET só disponibiliza dados do último ano, então o banco de dados só vai possuir dados desde um ano antes da primeira vez que a estação foi aberta. Tentei fazer um algoritmo para extrair os dados históricos dos arquivos .xls que o inmet envia quando solicitado, porem os arquivos não são padronizados e possuem uma série de inconsistências entre eles. Até hoje não encontrei uma base de dados horária completa do inmet para que eu pudesse implementar de alguma forma no pacote.
Realmente causa indignação essa dificuldade em obter os dados. Nem enviando email por meio do PPG Meteorologia da UFSM, de onde sou secretário, consegui esse acesso. É um investimento de milhões de reais sem retorno à sociedade.

**Comment by gabrielcocenza** [comment]
É indignante mesmo a falta de procedimentos, padronizações e atualizações das tecnologias de TI. Eu ainda custo a acreditar que não tem uma API para requisição de dados meteorológicos. Esse projeto é um tapa na cara desses políticos safados que colocam pessoas "políticas" em cargos técnicos que acabam gerando produtos toscos para a sociedade.
